### ISSUE TITLE
Visible RCTAsyncLocalStorage_V1 folder in IOS while i allow user to see Documents Directory to access Downloaded files. 

### ISSUE THREAD

**Issue by ahmad6242** [react-native-community/async-storage#222]
## Motivation

This case is only for IOS devices because in android we can save files in many other locations.(i am using RNFetchBlob to save files)
but in IOS it is only allowing to save files in documents directory. 

From the Application User can download PDF files, i am storing these files in documents directory, 
i am allowing this in info plist so user can access and open the Downloaded files.

<key>UIFileSharingEnabled</key>
<true/>
<key>UISupportsDocumentBrowser</key>
<true/>
<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>
 

in that directory we have folder called RCTAsyncLocalStorage_V1 in which all the locally stored data is there in a manifest.json file
this allows user to see all the raw data that can be used to do some hacking or playing around with things. 

## Description

is there any other way possible that we hide that directory or use some other method rather than crating a file to store data locally. 

## New feature implementation

If we are able to implement such thing we can hide sensitive data from the end users. 

Please let me know if anything is possible here.

**Comment by JJMoon** [comment]
I guess there are some directories in iOS Apps. 
In RNFS [https://github.com/itinance/react-native-fs#constants] there is LibraryDirectoryPath.
Can it be used as an alternative?
Or.
Can it be invisible folder? (like .RCTAsyncLocalStorage)

**Comment by Krizzu** [comment]
@ahmad6242 sorry for late response,

Currently there's no way to change the destination directory for iOS

**Comment by topik96** [comment]
@ahmad6242 when u use LSSupportsOpeningDocumentsInPlace in iOS, i try hide manifest file

**Comment by tido64** [comment]
We've just merged #274 which should resolve this issue. The folder has been moved to Application Support. It would be great if you could try out latest master and let us know how it works for you.

@Krizzu, did we cut a new release yet?

**Comment by Krizzu** [comment]
@tido64 Not yet, I plan to do this soon.

**Comment by ybonnetain** [comment]
Hi There
Would you be so keen to tell me how the migration is handled. If I already have a manifest in /Documents on deployed instances, is it migrated to the app’s Library folder ?

**Comment by Krizzu** [comment]
I know it's not ideal, but [here's a code that does the migration.](https://github.com/react-native-async-storage/async-storage/blob/master/ios/RNCAsyncStorage.m#L333) It's well documented so it's easy to tell what's going on

**Comment by yash-sage** [comment]
Hi, I've enabled the same flag UISupportsDocumentBrowser and using the latest 1.14.1 version of @react-native-async-storage/async-storage. But, I can still see the RCTAsyncLocalStorage_V1 folder in iOS File Manager.
Is there a particular code that I need to modify to change the saved directory from Documents to Application Support

**Comment by Krizzu** [comment]
@yash-sage Hey,

No, the migration is handled at app start and no additional code is necessary. The `RCTAsyncLocalStorage_V1` in documents is one used by bundled Async Storage that comes with React Native - we don't remove it to not lose any data and avoid conflicts with dependencies still using bundled AS. The data from this folder is migrated to Application support and this Async Storage is using it.
